# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: aubo
  joint_model_group_pose: zero
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_joint
    - upperArm_joint
    - foreArm_joint
    - wrist1_joint
    - wrist2_joint
    - wrist3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: aubo_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint

aubo_controller:
  type: position_controllers/JointTrajectoryController
  joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  gains:
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upperArm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foreArm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1